name: bulksmszw
description: bulksmszw api, a port for bulksmszw-api python library. Send bulk sms using bulksmsweb services
version: 2.0.0-dev
author: Donald Chinhuru<donychinhuru@gmail.com>
homepage: https://github.com/DonnC/bulksmszw

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: